### PR TITLE
feat: new blog design

### PR DESCRIPTION
**Pull request by jeroenrinzema**
# Todo:
- [x] come up with subtitle for blog. Currently: "Placeholder subtitle"

### CODE REVIEW

**Comment by jeroenrinzema** [comment]
# Todo:
- [ ] come up with subtitle for blog. Currently: "Placeholder subtitle"

**Comment by jeqo** [comment]
What about something simple as "data integration" as subtitle? Or let's make a poll internally.
Could we get the about page in another issue?

**Comment by jeroenrinzema** [comment]
I updated the subtitle for now to "data integration"

**Comment by jeroenrinzema** [comment]
Created a new issue for creating a about page (#2)

**Pull request merged**
